export const EVENT_TYPES = {
  TIMER_STARTED: "TIMER_STARTED",
  TIMER_EXPIRED: "TIMER_EXPIRED",
  ASSESSMENT_SUBMITTED: "ASSESSMENT_SUBMITTED",
  TAB_SWITCH: "TAB_SWITCH",
  FULLSCREEN_EXIT: "FULLSCREEN_EXIT",
  COPY_ATTEMPT: "COPY_ATTEMPT",
  PASTE_ATTEMPT: "PASTE_ATTEMPT",
  IP_CHANGE_DETECTED: "IP_CHANGE_DETECTED",
};
